version: '3'
services:
  kafka-0:
    image: vepo/kafka:3.5.0
    hostname: kafka-0
    ports:
     - 9092:9092
     - 9093:9093
    environment:
      KAFKA_CLUSTER_ID: N0UOwvnVR7ORiwq0M4do9w
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://kafka-0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9095,3@kafka-2:9097
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_NUM_PARTITIONS: 150
  kafka-1:
    image: vepo/kafka:3.5.0
    hostname: kafka-1
    ports:
     - 9094:9094
     - 9095:9095
    environment:
      KAFKA_CLUSTER_ID: N0UOwvnVR7ORiwq0M4do9w
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9094,CONTROLLER://kafka-1:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9095,3@kafka-2:9097
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_NUM_PARTITIONS: 150
  kafka-2:
    image: vepo/kafka:3.5.0
    hostname: kafka-2
    ports:
     - 9096:9096
     - 9097:9097
    environment:
      KAFKA_CLUSTER_ID: N0UOwvnVR7ORiwq0M4do9w
      KAFKA_BROKER_ID: 3
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://:9096,CONTROLLER://kafka-2:9097
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9096
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9095,3@kafka-2:9097
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_NUM_PARTITIONS: 150
  produtor:
    image: produtor
    ##build:
    ##  context: ./produtor
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
  consumidor:
    image: consumidor
    ##build:
    ##  context: ./consumidor
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
  starvation-finder:
    image: starvation-finder
    ##build:
    ##  context: ./starvation-finder
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2